[build]
build = "x86_64-unknown-linux-gnu"

host = [
  "x86_64-unknown-linux-gnu",
]

target = [
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
]

docs = false
compiler-docs = false
vendor = true
submodules = false
extended = true

[rust]
channel = "stable"
codegen-units = 1
codegen-units-std = 1
debuginfo-level-std = 2
rpath = false

[install]
prefix = "/usr/libexec/rust"
sysconfdir = "/usr/libexec/rust/etc"

[target.aarch64-unknown-linux-gnu]
cc = "aarch64-thar-linux-gnu-gcc"
cxx = "aarch64-thar-linux-gnu-g++"
ar = "/usr/bin/aarch64-thar-linux-gnu-ar"
ranlib = "/usr/bin/aarch64-thar-linux-gnu-ranlib"
linker = "aarch64-thar-linux-gnu-gcc"
crt-static = false

[target.aarch64-unknown-linux-musl]
cc = "aarch64-thar-linux-musl-gcc"
cxx = "aarch64-thar-linux-musl-g++"
ar = "/usr/bin/aarch64-thar-linux-musl-ar"
ranlib = "/usr/bin/aarch64-thar-linux-musl-ranlib"
linker = "aarch64-thar-linux-musl-gcc"
musl-root = "/aarch64-thar-linux-musl/sys-root/usr"
crt-static = true
