[build]
target = [
  "aarch64-bottlerocket-linux-gnu",
  "aarch64-bottlerocket-linux-musl",
]

docs = false
compiler-docs = false
vendor = true
submodules = false
extended = true
tools = ["cargo"]

[rust]
channel = "stable"
codegen-units = 1
codegen-units-std = 1
debuginfo-level-std = 2
rpath = false

[install]
prefix = "/usr/libexec/rust"
sysconfdir = "/usr/libexec/rust/etc"

[target.aarch64-bottlerocket-linux-gnu]
cc = "aarch64-bottlerocket-linux-gnu-gcc"
cxx = "aarch64-bottlerocket-linux-gnu-g++"
ar = "/usr/bin/aarch64-bottlerocket-linux-gnu-ar"
ranlib = "/usr/bin/aarch64-bottlerocket-linux-gnu-ranlib"
linker = "aarch64-bottlerocket-linux-gnu-gcc"
crt-static = false

[target.aarch64-bottlerocket-linux-musl]
cc = "aarch64-bottlerocket-linux-musl-gcc"
cxx = "aarch64-bottlerocket-linux-musl-g++"
ar = "/usr/bin/aarch64-bottlerocket-linux-musl-ar"
ranlib = "/usr/bin/aarch64-bottlerocket-linux-musl-ranlib"
linker = "aarch64-bottlerocket-linux-musl-gcc"
musl-root = "/aarch64-bottlerocket-linux-musl/sys-root/usr"
crt-static = true
