[build]
build = "x86_64-unknown-linux-gnu"

host = [
  "x86_64-unknown-linux-gnu",
]

target = [
  "x86_64-unknown-linux-musl",
]

docs = false
compiler-docs = false
vendor = true
submodules = false
extended = true

[rust]
channel = "stable"
codegen-units = 1
codegen-units-std = 1
debuginfo-level-std = 2
rpath = false

[install]
prefix = "/usr/libexec/rust"
sysconfdir = "/usr/libexec/rust/etc"

[target.x86_64-unknown-linux-musl]
cc = "x86_64-bottlerocket-linux-musl-gcc"
cxx = "x86_64-bottlerocket-linux-musl-g++"
ar = "/usr/bin/x86_64-bottlerocket-linux-musl-ar"
ranlib = "/usr/bin/x86_64-bottlerocket-linux-musl-ranlib"
linker = "x86_64-bottlerocket-linux-musl-gcc"
musl-root = "/x86_64-bottlerocket-linux-musl/sys-root/usr"
crt-static = true
