[clarify.askalono]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x18785531 },
    { path = "NOTICE", hash = 0x96b3ea7d },
]
skip-files = [
    "src/license.rs" # source code named "license"...
]

[clarify.backtrace-sys]
# backtrace-sys is MIT/Apache-2.0, libbacktrace is BSD-3-Clause
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "src/libbacktrace/LICENSE", hash = 0x0ce09262 },
]

[clarify.bstr]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "COPYING", hash = 0x278afbcf },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x462dee44 },
    { path = "src/unicode/data/LICENSE-UNICODE", hash = 0x70f7339 },
]

[clarify.crossbeam-channel]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xbc436f08 },
    { path = "LICENSE-THIRD-PARTY", hash = 0x847bf39 },
]

[clarify.crossbeam-queue]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xbc436f08 },
    { path = "LICENSE-THIRD-PARTY", hash = 0x7e40bc60 },
]

[clarify.regex]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
]
skip-files = [
    "src/testdata/LICENSE", # we aren't using the test data
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.unicode-ident]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE-UNICODE", hash = 0x9698cbbe },
]

[clarify.zstd-safe]
# zstd-safe is MIT OR Apache-2.0
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
    { path = "LICENSE.Mit", hash = 0xa237d234 },
]
skip-files = [
    "zstd/COPYING", # copy of the GPLv2 we are not choosing from libzstd's dual license
    "zstd/build/LICENSE", # empty file
    "zstd/contrib/linux-kernel/COPYING", # kernel source and patches for adding zstd (?!), not used
]

[clarify.zstd-sys]
# zstd-sys is MIT OR Apache-2.0
# libzstd is GPL-2.0-only OR BSD-3-Clause (selecting BSD-3-Clause)
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
    { path = "LICENSE.Mit", hash = 0xa237d234 },
    { path = "LICENSE.BSD-3-Clause", hash = 0xc9f5c4f6 },
    { path = "zstd/LICENSE", hash = 0x79cda15 },
]
skip-files = [
    "zstd/COPYING", # copy of the GPLv2 we are not choosing from libzstd's dual license
    "zstd/build/LICENSE", # empty file
    "zstd/contrib/linux-kernel/COPYING", # kernel source and patches for adding zstd (?!), not used
]
