[licenses]
unlicensed = "deny"

# Deny licenses unless they are specifically listed here
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSL-1.0",
    "MIT",
    "Unlicense",
]

# FIXME: Remove this when a license is assigned for first-party packages
[licenses.private]
ignore = true
