[clarify.bstr]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "COPYING", hash = 0x278afbcf },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x462dee44 },
    { path = "src/unicode/data/LICENSE-UNICODE", hash = 0x70f7339 },
]

[clarify.bzip2-sys]
expression = "(MIT OR Apache-2.0) AND bzip2-1.0.6"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x9374b940 },
    { path = "bzip2-1.0.8/LICENSE", hash = 0x71e74485 },
]

[clarify.cargo-make]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/static.files/COPYRIGHT-000000008a1f0d17.txt",
    "docs/api/static.files/FiraSans-LICENSE-000000004f3fb3ba.txt",
    "docs/api/static.files/LICENSE-APACHE-00000000be5b60d4.txt",
    "docs/api/static.files/LICENSE-MIT-00000000cc9db09c.txt",
    "docs/api/static.files/NanumBarunGothic-LICENSE-000000008feec719.txt",
    "docs/api/static.files/SourceCodePro-LICENSE-00000000fb612b27.txt",
    "docs/api/static.files/SourceSerif4-LICENSE-00000000b79e562a.md",
]

[clarify.ci_info]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/static.files/COPYRIGHT-00000000b04765ec.txt",
    "docs/api/static.files/FiraSans-LICENSE-000000004a115331.txt",
    "docs/api/static.files/LICENSE-APACHE-00000000be5b60d4.txt",
    "docs/api/static.files/LICENSE-MIT-00000000cc9db09c.txt",
    "docs/api/static.files/NanumBarunGothic-LICENSE-0000000042e1adda.txt",
    "docs/api/static.files/SourceCodePro-LICENSE-0000000063ca2e38.txt",
    "docs/api/static.files/SourceSerif4-LICENSE-00000000d7b83a85.md",
]

[clarify.cliparser]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerif4-LICENSE.md",
]

[clarify.envmnt]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerif4-LICENSE.md",
]

[clarify.fsio]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerif4-LICENSE.md",
]

[clarify.git_info]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerifPro-LICENSE.md",
]

[clarify.regex]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
]
skip-files = [
    "src/testdata/LICENSE", # we aren't using the test data
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.run_script]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/static.files/COPYRIGHT-00000000b04765ec.txt",
    "docs/api/static.files/FiraSans-LICENSE-000000004a115331.txt",
    "docs/api/static.files/LICENSE-APACHE-00000000be5b60d4.txt",
    "docs/api/static.files/LICENSE-MIT-00000000cc9db09c.txt",
    "docs/api/static.files/NanumBarunGothic-LICENSE-0000000042e1adda.txt",
    "docs/api/static.files/SourceCodePro-LICENSE-0000000063ca2e38.txt",
    "docs/api/static.files/SourceSerif4-LICENSE-00000000d7b83a85.md",
]

[clarify.rust_info]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/noto-sans-kr-v13-korean-regular-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerif4-LICENSE.md",
]

[clarify.shell2batch]
expression = "Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xd9300aad },
]
skip-files = [
    "docs/api/COPYRIGHT.txt",
    "docs/api/FiraSans-LICENSE.txt",
    "docs/api/LICENSE-APACHE.txt",
    "docs/api/LICENSE-MIT.txt",
    "docs/api/NanumBarunGothic-LICENSE.txt",
    "docs/api/SourceCodePro-LICENSE.txt",
    "docs/api/SourceSerif4-LICENSE.md",
]

[clarify.typenum]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xa4618a29 },
    { path = "LICENSE-MIT", hash = 0xb9f15462 },
    { path = "LICENSE-APACHE", hash = 0x91d5a0a7 },
]

[clarify.unicode-ident]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0xb5518783 },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE-UNICODE", hash = 0x9698cbbe },
]
