[clarify.backtrace-sys]
# backtrace-sys is MIT/Apache-2.0, libbacktrace is BSD-3-Clause
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "src/libbacktrace/LICENSE", hash = 0x0ce09262 },
]

[clarify.bstr]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "COPYING", hash = 0x28398560 },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x462dee44 },
    { path = "src/unicode/data/LICENSE-UNICODE", hash = 0x70f7339 },
]

[clarify.crossbeam-channel]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xbc436f08 },
    { path = "LICENSE-THIRD-PARTY", hash = 0x847bf39 },
]

[clarify.regex]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
]
skip-files = [
    "src/testdata/LICENSE", # we aren't using the test data
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.encoding_rs]
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x18785531 },
    { path = "LICENSE-MIT", hash = 0xafaec4cb },
    { path = "LICENSE-WHATWG", hash = 0xbcb87a0c },
]
skip-files = [ "COPYRIGHT"] # this file describes what licenses apply to the sources, and when they apply

[[clarify.regex-automata]]
version = "^0.1"
expression = "Unlicense OR MIT"
license-files = [
    { path = "LICENSE-MIT", hash = 0x616d8a83 },
    { path = "UNLICENSE", hash = 0x87b84020 },
]
skip-files = [
    # these licenses apply to the test data, which we don't distribute,
    "data/tests/fowler/LICENSE",
    "data/fowler-tests/LICENSE",
    # this file describes what licenses apply to the sources, and when they apply
    "COPYING"
]

[[clarify.regex-automata]]
version = "^0.3"
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
]

[clarify.unicode-ident]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0xb5518783 },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE-UNICODE", hash = 0x9698cbbe },
]
